### ISSUE TITLE
Release section says latest release was 2.0.3 while npm has 2.1.0

### ISSUE THREAD

**Issue by saurabhsablaka** [auth0/idtoken-verifier#118]
I have a question (not related to functionality though), on npm I could locate latest [version ](https://www.npmjs.com/package/idtoken-verifier) as 2.1.0 while here in [release](https://github.com/auth0/idtoken-verifier/releases) section the latest version I could find is 2.0.3. Am I missing something here ?  Just wanted to be sure that I am using the correct version / package.

**Comment by stevehobbsdev** [comment]
Thanks for raising @saurabhsablaka, unfortunately I had neglected to publish the latest GitHub release, which I have now done. [2.1.0 is the correct version](https://github.com/auth0/idtoken-verifier/releases/tag/v2.1.0).

Thanks!
