### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by kousher-alam** [auth0/idtoken-verifier#147]
ReferenceError: XMLHttpRequest is not defined
    at C:\projects\OI-Tracking\graphql\node_modules\idtoken-verifier\build\idtoken-verifier.js:1:34591
    at new Promise (<anonymous>)
    at S (C:\projects\OI-Tracking\graphql\node_modules\idtoken-verifier\build\idtoken-verifier.js:1:34559)
    at C:\projects\OI-Tracking\graphql\node_modules\idtoken-verifier\build\idtoken-verifier.js:1:39970

**Comment by stevehobbsdev** [comment]
Please can you supply more information here. What browser or environment are you using this in? `XMLHttpRequest` is an API built into browsers, which is the intended target for this SDK, so should be available.
