### ISSUE TITLE
Support to fetch the JWKS from different location than /.well-known/jwks.json

### ISSUE THREAD

**Issue by neo182** [auth0/idtoken-verifier#18]
It is well-mentioned that jwksCache: the verifier will try to fetch the JWKS from the /.well-known/jwks.json endpoint each time it verifies a token. But this may not be always the case. This is the sitution for the company I am working on. Should such an assumption be so rigid? What about providing support for fetching the keys from other location? What about taking this param as a config param?

**Comment by luisrudge** [comment]
ACcording to the spec, this is possible, but it's not on our radar as of now. Do you want to send a PR with that?
