### ISSUE TITLE
Type definitions for TypeScript usage

### ISSUE THREAD

**Issue by markusl** [auth0/idtoken-verifier#32]
Hi!

Would it be possible to include the TypeScript type definitions within the library to make the usage even easier? 

BR,
Markus

**Comment by luisrudge** [comment]
We're moving more and more to typescript. Hopefully we can migrate this lib one day 😬

**Comment by aecz** [comment]
Why closing this issue? How can I get notified of progress?
Subscribing to a closed issue does not seem right :)
Also migrating to Typescript is not strictly needed. Only adding typings would be enough.

**Comment by ItalyPaleAle** [comment]
I made a PR for this: https://github.com/auth0/idtoken-verifier/pull/122
