### ISSUE TITLE
Use of window in unfetch causes ReferenceError

### ISSUE THREAD

**Issue by jdsaund** [auth0/idtoken-verifier#38]
### Description
We've noticed our CI runner has been crashing since the release of version 1.3.0. Error message:
```
ReferenceError: window is not defined
```

Since this package is listed on npmjs, I assume there shouldn't be a dependency on window which doesn't exist in node.

The problem is introduced with version 1.3.0 through use of `isomophic-unfetch` package which depends on the existence of window global:
https://github.com/developit/unfetch/blob/92d9203e02edbd7ac6788be41dd629b5c8247299/packages/isomorphic-unfetch/browser.js#L1

Reverting to v1.2.0 solves the problem for now.

### Environment

Please provide the following:

- Version of `idtoken-verifier` used: 1.3.0
- Browser version tested: N/A (nodejs)
- Any other elevant environmental versions: Running in docker container for CI. Not seeing the issue on local machine.
- Additional modules/plugins/add-ons that might be affecting your instance:

### Reproduction

Requiring this package will cause immediate error:
```
[05:30:37] ReferenceError: window is not defined
    at Object.<anonymous> (/builds/<project path>/node_modules/idtoken-verifier/build/idtoken-verifier.js:1:29120)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/builds/<project path>/<file>.js)
```

**Comment by luisrudge** [comment]
Yup, we saw that too. Here's how we fixed it: https://github.com/auth0/auth0.js/pull/947/commits/ce22ef497dee8bc61861c174709286363c2eee90

**Comment by tnolet** [comment]
Yeah, this broke my build on Heroku. I don't really understand what you mean with "here's how we fixed it".  Any tips?

**Comment by tnolet** [comment]
For anyone bumping into this, you need to upgrade to the latest https://www.npmjs.com/package/auth0-js package, 9.10.4 as of writing.

**Comment by luisrudge** [comment]
@tnolet what version were you using before?

**Comment by tnolet** [comment]
@luisrudge I was on 9.6.0. That broke due to the idtoken-verifier dependency.

**Comment by luisrudge** [comment]
Did you get the same error? `window is not defined`? Was it during tests or something?

**Comment by tnolet** [comment]
Yes, it was the exact error. I noticed when my Heroku app crashed at launch after pushing an update.

**Comment by BarryCarlyon** [comment]
This is still an issue.

I'm not using auth0 I'm just using idtoken-verifier to verify for another service.

auth0-js is not a dependency of mine or of idtoken-verifier

So the fix noted above (upgrade auth0-js) is not suitable, as I don't have auth0-js in use.

**Comment by 0190** [comment]
@BarryCarlyon I assume you'll have to use idtoken-verifier version 1.3.1.
This is what the auth0-js upgrade does - mainly upgrades the version of this dependency to 1.3.1.

**Comment by luisrudge** [comment]
@BarryCarlyon this library is meant for the browser only. You can use https://github.com/auth0/node-jsonwebtoken in nodejs.

**Comment by nikosalonen** [comment]
Wouldn't using [Isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch) fix this?

> Switches between unfetch & node-fetch for client & server.
