### ISSUE TITLE
After upgrading the dependency in Node app causes ReferenceError 'XMLHttpRequest is not defined'

### ISSUE THREAD

**Issue by markusl** [auth0/idtoken-verifier#67]
I tried to upgrade the library to latest version in a Nodejs express application and it now fails with ReferenceError 'XMLHttpRequest is not defined'. Is this possibly caused by changes in the library or should I modify my application code somehow?

**Comment by luisrudge** [comment]
Indeed it is. nodejs is not supported by this library. You should use https://github.com/auth0/node-jsonwebtoken in the server.
