### ISSUE TITLE
Validate audience using array contain when "aud" claim is an array

### ISSUE THREAD

**Issue by jaroslaw-gorecki** [auth0/idtoken-verifier#74]
Would it be possible to add support for proper audience validation when id_token "aud" claim is an array of strings?
Currently the library accepts audience as string and does the exact match, what causes validation to fail.

**Comment by dulowski-marek** [comment]
Note that as per https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation in this case the presence of `azp` claim containing `client_id`, listed in `aud` array should also be validated.

I can submit a PR, if you're happy with that.

**Comment by joshcanhelp** [comment]
@jaroslaw-gorecki @dulowski-marek - Thanks for the report and the reply here. We're working on better token validation across all of our libraries, this one included. You should see a PR for that soon 👍

**Comment by stevehobbsdev** [comment]
This is now fixed in the latest version.

**Comment by jaroslaw-gorecki** [comment]
Thanks 👍
