### ISSUE TITLE
angular 8 and tsconfig target es2015 fails fall back to es5 needed

### ISSUE THREAD

**Issue by theresiasnow** [auth0/idtoken-verifier#75]
### Description

Angular 8 app running in latest chrome gives this console log when using target es2015 in tsconfig.json

`AppComponent.html:8 ERROR TypeError: this.getTokenVerifier(...).decode is not a function`

### Reproduction

Run an angular 8 app using this module. Fail.
setting es5 in tsconfig.json makes it work.

### Environment

version 1.4.1
angular 8
chrome 77.0.xxx

**Comment by luisrudge** [comment]
When you debug your code, what is `this.getTokenVerifier` and why is that different when you switch to ES5?
