### ISSUE TITLE
node support

### ISSUE THREAD

**Issue by itajaja** [auth0/idtoken-verifier#8]
Hi, I am trying to use this library for verifying the validity of jwt tokens on my node application. I was wondering why the description says "meant for the browser". Is there anything wrong in using this library server side for validating the tokens?
thanks :)

**Comment by hzalaz** [comment]
Its because will lack some features that are not needed in the browser. I'd recommend using https://www.npmjs.com/package/jsonwebtoken instead

**Comment by itajaja** [comment]
The verifier in jsonwebtoken accepts a secret, not an issuer from which to get `/.well-known/jwks.json` so it seems like I'd have to implement that feature my self, but idtoken-verifier already offers this, and I was hoping I didn't have to write that logic myself. am I missing something?

**Comment by hzalaz** [comment]
OK you need support for JWKS not for verification itself. You can use https://github.com/auth0/node-jwks-rsa for that. But remember that this lib and node-jwks-rsa only work with RSA for now

**Comment by hzalaz** [comment]
You can then supply the key to the jsonwebtoken lib
